### ISSUE TITLE
add miatoll device

### ISSUE THREAD

**Issue by 99degree** [sm7150-mainline/nightly-builds#1]
hi there,

I found that you setup a great auto build sys in github action and is useful. could you please consider add one more device into the build system? just in case you have plan for that, please take a look below suggestions.

(1) please build miatoll target with --no-sparse --split that people like me can flash the img into sdcard (instead of internal ufs). the reason behind (--split) is i found out I can only use this boot method to get in gnome phosh, the one pmos_root_uuid wont work my side. i examed the resulting img, can't use losetup to mount under wsl, the same happened to https://postmarketos.org/download/ for community build. to workaround it, i use the official build of pinephone img.......fine, very interesting. the remaining is the fw for boot drm kms driver below:
https://github.com/99degree/firmware-xiaomi-miatoll

(2) if possible, please help to merge the panel driver your tree too. sounds not so funny to build every time to check breakage.....after merge..... well, the panel for nt36675-tianma is lived in the patch of 712fd0d4223f93fe4a3b0858315a27e68723b208

i had make some modification for device (pmaport), but not in a good maintainence shape. hope this helps.
https://github.com/99degree/postmarket-nightly-builds
https://github.com/99degree/pmaports

btw, the pmos boot to phosh is nice. i took a shot of it and dual boot with los20. 
https://www.youtube.com/watch?v=fz7Zj4eY4iY

best regards

**Comment by Gelbpunkt** [comment]
We will only add devices that share the kernel with ours, anything else doesn't really make sense to add. Miatoll is SM7125 and therefore out of scope for our kernel fork.
